USE [Stage]
GO

/****** Object:  Index [IX_PT]    Script Date: 07/26/2019 15:52:26 ******/
CREATE NONCLUSTERED INDEX [IX_PT] ON [lg].[PT_n] 
(
	[estado] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


/****** Object:  Index [IX_PT_codigo]    Script Date: 07/26/2019 15:52:34 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_PT_codigo] ON [lg].[PT_n] 
(
	[tipo] ASC,
	[Almacen] ASC,
	[mes] ASC,
	[no_pedido] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

/****** Object:  Index [IX_PT_estado_ped]    Script Date: 07/26/2019 15:52:57 ******/
CREATE NONCLUSTERED INDEX [IX_PT_estado_ped] ON [lg].[PT_n] 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

/****** Object:  Index [IX_PT_tipo]    Script Date: 07/26/2019 15:53:21 ******/
CREATE NONCLUSTERED INDEX [IX_PT_tipo] ON [lg].[PT_n] 
(
	[tipo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

