INSERT INTO [Stage].[dbo].[stockHist]
           ([fecha]
           ,[agen]
           ,[agesuc]
           ,[item]
           ,[itedes]
           ,[iteun]
           ,[stock]
           ,[cu]
           ,[iteori]
           ,[itecli]
           ,[iteubi]
           ,[itecen]
           ,[ciudad])
 
SELECT 
	  '2019-02-28'
	  ,[agen]
      ,[agesuc]
      ,[item]
      ,[itedes]
      ,[iteun]
      ,[stock]
      ,[cu]
      ,[iteori]
      ,[itecli]
      ,[iteubi]
      ,[itecen]
      ,[ciudad]
  FROM [Stage].[dbo].[stockTemp]
