INSERT INTO [Stage].[dbo].[ventas]
           ([CIUDAD]
           ,[AGENCIA]
           ,[TIPO]
           ,[PERIODO]
           ,[NUMFACT]
           ,[DOCUMENTO]
           ,[FECHA]
           ,[MES]
           ,[ITEM]
           ,[DESCRIPCION]
           ,[CLIENTE]
           ,[VE]
           ,[NOMBREVENDEDOR]
           ,[CANTIDAD]
           ,[IMPORTEBS]
           ,[UN]
           ,[PROVEEDOR]
           ,[LINEA]
           ,[CUENTA]
           ,[DESCRIPCION2]
           ,[NOMBREUN]
           ,[NOMBREAG])
 SELECT  [CIUDAD]
      ,[AGENCIA]
      ,[TIPO]
      ,[PERIODO]
      ,[NUMFACT]
      ,[DOCUMENTO]
      ,[FECHA]
      ,[MES]
      ,[ITEM]
      ,[DESCRIPCION]
      ,[CLIENTE]
      ,[VE]
      ,[NOMBREVENDEDOR]
      ,[CANTIDAD]
      ,[IMPORTEBS]
      ,[UN]
      ,[PROVEEDOR]
      ,[LINEA]
      ,[CUENTA]
      ,[DESCRIPCION2]
      ,[NOMBREUN]
      ,[NOMBREAG]
  FROM [Stage].[dbo].[cvf]
  